version: "3.5"
services:
  postgres:
    image: xuxiaoyu/postgres:15.1-bullseye-jieba 
    container_name: postgres
    environment:
      POSTGRES_DB: blog2
      POSTGRES_PASSWORD: blog2pass
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h postgres"]
      interval: 5s
      timeout: 30s
      retries: 15
  blog2:
    image: xuxiaoyu/blog2:latest
    container_name: blog2
    environment:
      SERVRENAME: blog2
      GIN_MODE: release
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blog2pass
      POSTGRES_DB: blog2
      ADMIN_USER: admin
      ADMIN_PASSWORD: adminpass
    ports:
      - 8080:8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy 
    links:
      - postgres
