version: "3.5"
services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: blog2
      POSTGRES_PASSWORD: blog2Pass
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    restart: always

  blog2:
    image: xuxiaoyu/blog2:latest
    container_name: blog2
    environment:
      SERVRENAME: blog2
      GIN_MODE: release
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blog2Pass
      POSTGRES_DB: blog2
    ports:
      - 8080:8080
    restart: always
