// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package backend

import (
	"github.com/fengshux/blog2/backend/conf"
	"github.com/fengshux/blog2/backend/controller"
	"github.com/fengshux/blog2/backend/db"
	"github.com/fengshux/blog2/backend/service"
)

// Injectors from wire.go:

func NewRegister() (*Register, error) {
	confConf := conf.NewConf()
	gormDB := db.NewPG(confConf)
	baseService := service.NewBaseService(gormDB)
	user := service.NewUser(baseService)
	controllerUser := controller.NewUser(user)
	post := service.NewPost(baseService)
	controllerPost := controller.NewPost(post)
	register := newRegister(controllerUser, controllerPost)
	return register, nil
}
