postgres:
  host: ${POSTGRES_HOST|localhost}
  port: ${POSTGRES_PORT|5431}
  user: ${POSTGRES_USER|postgres}
  password: ${POSTGRES_PASSWORD|123456}
  db: ${POSTGRES_DB|postgres}
auth:
  secret: ${AUTH_SECRET|SecretYouShouldHide}
  expires: ${AUTH_EXPIRES|36000}
admin:
  user: ${ADMIN_USER|admin}
  password: ${ADMIN_PASSWORD|adminpass}
